# -*- coding: utf-8 -*-
"""
古史_v3_共和新生 · 电子书生成器
Generated by Mavis · MiniMax Code
用法：python generate_v3_ebook.py
输出：DOCX（桌面） + MD（屏幕阅读）
"""

import sys
import os

# ── 加载数据文件 ────────────────────────────────────────────
def load_episodes():
    """加载所有四集 Python 数据模块"""
    episodes = []
    script_dir = os.path.dirname(os.path.abspath(__file__))

    episode_files = [
        "古史_v3_ep01_天朝崩塌.py",
        "古史_v3_ep02_帝国挽歌.py",
        "古史_v3_ep03_觉醒年代.py",
        "古史_v3_ep04_共和新生.py",
    ]

    for fname in episode_files:
        fpath = os.path.join(script_dir, fname)
        namespace = {}
        with open(fpath, "r", encoding="utf-8") as f:
            content = f.read()
        exec(compile(content, fpath, "exec"), namespace)
        episodes.append(namespace["get_data"]())

    return episodes


# ── Markdown 渲染器 ───────────────────────────────────────────
class ModernHistoryMD:
    """输出 Markdown 版电子书"""

    def __init__(self, episodes):
        self.episodes = episodes

    def render(self):
        lines = []
        lines += self._header()
        for ep in self.episodes:
            lines += self._ep(ep)
        return "\n".join(lines)

    def _header(self):
        return [
            "# 共和新生",
            "## 1840-1949：从天朝崩塌到人民共和国",
            "",
            "**卷三 · 中国近现代史**",
            "",
            "---\n",
            "",
            "## 内容概要",
            "",
            "| 集 | 标题 | 时间跨度 | 核心问题 | 知识链 | 高频点 | 核心概念 |",
            "|---|---|---|---|---|---|---|",
            "| Ep01 | 天朝崩塌 | 1840-1864 | 洋务运动能否救亡？ | 4条 | 8个 | 5个 |",
            "| Ep02 | 帝国挽歌 | 1864-1912 | 制度变革为何艰难？ | 4条 | 8个 | 5个 |",
            "| Ep03 | 觉醒年代 | 1912-1935 | 新道路在哪里？ | 4条 | 9个 | 4个 |",
            "| Ep04 | 共和新生 | 1931-1949 | 新中国为何必然？ | 4条 | 9个 | 5个 |",
            "",
            "**时间线总览**：1840年鸦片战争 → 1912年清帝退位 → 1949年新中国成立",
            "**109年苦难辉煌 · 完整覆盖高考中国近现代史全部高频考点**",
            "",
            "---\n",
        ]

    def _ep(self, ep):
        lines = []
        ep_num = ep["ep"]
        lines.append(f"\n# 第{ep_num}集 · {ep['title']}")
        lines.append(f"## {ep['subtitle']}")
        lines.append(f"**时间跨度**：{ep['time_period']}（{ep['duration']}）\n")

        # ── 第一幕：时间线 ────────────────────────────────────
        lines.append("## 第一幕 · 时间线\n")
        tl = ep["timeline"]
        lines.append(f"**总述**：{tl['overview'].strip()}\n")
        lines.append("| 年代 | 事件 | 描述 | 意义 |")
        lines.append("|---|---|---|---|")
        for ev in tl["events"]:
            lines.append(
                f"| {ev['year']} | **{ev['title']}** | {ev['description'][:80]}…… | {ev['significance']} |"
            )
        lines.append("")

        # ── 第二幕：艺术问题 ────────────────────────────────────
        aq = ep["art_question"]
        lines.append("## 第二幕 · 艺术问题\n")
        lines.append(f"**设问**：{aq['question']}\n")
        lines.append(f"{aq['context'].strip()}\n")
        lines.append(f"> **洞察**：{aq['insight'].strip()}\n")

        # ── 第三幕：当代回响 ────────────────────────────────────
        ce = ep["contemporary_echo"]
        lines.append("## 第三幕 · 当代回响\n")
        lines.append(f"**总述**：{ce['overview'].strip()}\n")
        for i, pt in enumerate(ce["echo_points"], 1):
            lines.append(f"### {i}. {pt['modern_issue']}")
            lines.append(f"**历史关联**：{pt['historical_connection']}")
            lines.append(f"**当代启示**：{pt['contemporary_reflection']}\n")

        # ── 第四幕：春秋笔法 ────────────────────────────────────
        sat = ep["spring_autumn_transition"]
        lines.append("## 第四幕 · 春秋笔法\n")
        if sat.get("from_this_volume_ep1"):
            prev = sat["from_this_volume_ep1"]
            lines.append(f"**上接**：{prev['preceding_ep']}")
            lines.append(f"{prev['transition_sentence'].strip()}\n")
        if sat.get("to_ep2"):
            nxt = sat["to_ep2"]
            lines.append(f"**下承**：{nxt['next_ep']} — {nxt['forward_context'].strip()}\n")
        if sat.get("to_modern_history") and sat["to_modern_history"].get("series_conclusion"):
            sc = sat["to_modern_history"]["conclusion_context"]
            lines.append(f"### 全系列结语\n{sc.strip()}\n")

        # ── 附录：知识链 ────────────────────────────────────────
        chains = ep["knowledge_chains"]
        lines.append("## 附录 · 知识链\n")
        for ch_id, ch in chains.items():
            lines.append(f"### {ch['chain_id']}：{ch['chain_title']}")
            lines.append(f"**类型**：{ch['chain_type']}")
            lines.append(f"**核心规律**：{ch['core_pattern']}\n")
            lines.append(f"{ch['narrative'].strip()}\n")
            lines.append("**关键节点**：")
            for nd in ch["key_nodes"]:
                lines.append(f"- {nd['node']} → {nd['answer']}")
            lines.append("")

        # ── 高频考点 ───────────────────────────────────────────
        lines.append("### 高频考点速记\n")
        for pt in ep["high_frequency_points"]:
            lines.append(f"- {pt}")
        lines.append("")

        # ── 核心概念 ───────────────────────────────────────────
        lines.append("### 核心概念\n")
        for cpt in ep["key_concepts"]:
            lines.append(f"**{cpt['concept']}**：{cpt['definition'].strip()}")
            lines.append(f"*{cpt['exam_tip']}*\n")

        lines.append("\n---\n")
        return lines

    def save(self, out_path):
        content = self.render()
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(content)
        size = os.path.getsize(out_path)
        print(f"[MD] 写入成功：{out_path}（{size/1024:.1f} KB）")


# ── DOCX 渲染器 ──────────────────────────────────────────────
class ModernHistoryDOCX:
    """输出 DOCX 版电子书"""

    def __init__(self, episodes):
        self.episodes = episodes

    def render(self, out_path):
        try:
            from docx import Document
            from docx.shared import Pt, RGBColor, Inches
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            from docx.oxml.ns import qn
        except ImportError:
            print("[DOCX] python-docx 未安装，跳过 DOCX 生成（可 pip install python-docx）")
            return

        doc = Document()

        # 全局样式
        style = doc.styles["Normal"]
        style.font.name = "宋体"
        style.font.size = Pt(11)
        style._element.rPr.rFonts.set(qn("w:eastAsia"), "宋体")

        def add_heading(doc, text, level):
            h = doc.add_heading(text, level=level)
            for run in h.runs:
                run.font.name = "黑体"
                run._element.rPr.rFonts.set(qn("w:eastAsia"), "黑体")
                if level == 1:
                    run.font.size = Pt(18)
                    run.font.color.rgb = RGBColor(0x8B, 0x00, 0x00)
                elif level == 2:
                    run.font.size = Pt(15)
                    run.font.color.rgb = RGBColor(0x55, 0x00, 0x00)
                elif level == 3:
                    run.font.size = Pt(13)
                    run.font.color.rgb = RGBColor(0x33, 0x33, 0x33)
            return h

        def add_para(doc, text, bold=False, indent=False):
            p = doc.add_paragraph(text)
            p.paragraph_format.first_line_indent = Inches(0.3) if indent else None
            for run in p.runs:
                run.font.size = Pt(11)
                run.font.bold = bold
                run.font.name = "宋体"
                run._element.rPr.rFonts.set(qn("w:eastAsia"), "宋体")
            return p

        def add_bullet(doc, text):
            p = doc.add_paragraph(text, style="List Bullet")
            for run in p.runs:
                run.font.size = Pt(10.5)
                run.font.name = "宋体"
                run._element.rPr.rFonts.set(qn("w:eastAsia"), "宋体")
            return p

        def add_table_row(table, cells):
            row = table.add_row()
            for i, (cell, w) in enumerate(zip(cells, [0.8, 1.2, 3.0, 1.5])):
                c = row.cells[i]
                c.text = cell
                for para in c.paragraphs:
                    for run in para.runs:
                        run.font.size = Pt(9.5)
                        run.font.name = "宋体"
                        run._element.rPr.rFonts.set(qn("w:eastAsia"), "宋体")
            return row

        # 封面
        doc.add_paragraph()
        h = doc.add_heading("共和新生", 0)
        for run in h.runs:
            run.font.size = Pt(28)
            run.font.color.rgb = RGBColor(0x8B, 0x00, 0x00)
            run.font.name = "黑体"
            run._element.rPr.rFonts.set(qn("w:eastAsia"), "黑体")
        h = doc.add_heading("1840-1949：从天朝崩塌到人民共和国", 1)
        for run in h.runs:
            run.font.name = "黑体"
            run._element.rPr.rFonts.set(qn("w:eastAsia"), "黑体")
            run.font.color.rgb = RGBColor(0x55, 0x00, 0x00)
        add_para(doc, "卷三 · 中国近现代史 · 完整剧本", bold=True)
        add_para(doc, "四集 · 十六链 · 一百零九年苦难辉煌", bold=True)
        doc.add_page_break()

        # 目录
        add_heading(doc, "内容概要", 1)
        tbl = doc.add_table(rows=1, cols=6)
        tbl.style = "Table Grid"
        hdr = tbl.rows[0]
        for i, h_text in enumerate(["集", "标题", "时间跨度", "核心问题", "知识链", "高频点"]):
            hdr.cells[i].text = h_text
            for p in hdr.cells[i].paragraphs:
                for r in p.runs:
                    r.font.bold = True
                    r.font.size = Pt(9)
        ep_summary = [
            ("Ep01", "天朝崩塌", "1840-1864", "洋务运动能否救亡？", "4条", "8个"),
            ("Ep02", "帝国挽歌", "1864-1912", "制度变革为何艰难？", "4条", "8个"),
            ("Ep03", "觉醒年代", "1912-1935", "新道路在哪里？", "4条", "9个"),
            ("Ep04", "共和新生", "1931-1949", "新中国为何必然？", "4条", "9个"),
        ]
        for row_data in ep_summary:
            r = tbl.add_row()
            for i, txt in enumerate(row_data):
                r.cells[i].text = txt
                for p in r.cells[i].paragraphs:
                    for run in p.runs:
                        run.font.size = Pt(9)
        doc.add_paragraph()
        add_para(doc, "时间线总览：1840年鸦片战争 → 1912年清帝退位 → 1949年新中国成立")
        add_para(doc, "109年苦难辉煌 · 完整覆盖高考中国近现代史全部高频考点")
        doc.add_page_break()

        # 各集
        for ep in self.episodes:
            ep_num = ep["ep"]
            add_heading(doc, f"第{ep_num}集 · {ep['title']}", 1)
            add_para(doc, ep["subtitle"], bold=True)
            add_para(doc, f"时间跨度：{ep['time_period']}（{ep['duration']}）", bold=True)
            doc.add_paragraph()

            # ── 第一幕：时间线 ──────────────────────────────────
            add_heading(doc, "第一幕 · 时间线", 2)
            tl = ep["timeline"]
            add_para(doc, tl["overview"].strip(), indent=True)
            tbl = doc.add_table(rows=1, cols=4)
            tbl.style = "Table Grid"
            hdr = tbl.rows[0]
            for i, h_text in enumerate(["年代", "事件", "描述", "意义"]):
                hdr.cells[i].text = h_text
                for p in hdr.cells[i].paragraphs:
                    for r in p.runs:
                        r.font.bold = True
                        r.font.size = Pt(9)
            for ev in tl["events"]:
                add_table_row(tbl, [ev["year"], ev["title"], ev["description"], ev["significance"]])
            doc.add_paragraph()

            # ── 第二幕：艺术问题 ────────────────────────────────
            add_heading(doc, "第二幕 · 艺术问题", 2)
            aq = ep["art_question"]
            add_para(doc, f"设问：{aq['question']}", bold=True)
            add_para(doc, aq["context"].strip(), indent=True)
            p = doc.add_paragraph()
            run = p.add_run(f"洞察：{aq['insight'].strip()}")
            run.bold = True
            run.italic = True
            run.font.size = Pt(10.5)
            doc.add_paragraph()

            # ── 第三幕：当代回响 ────────────────────────────────
            add_heading(doc, "第三幕 · 当代回响", 2)
            ce = ep["contemporary_echo"]
            add_para(doc, ce["overview"].strip(), indent=True)
            for i, pt in enumerate(ce["echo_points"], 1):
                add_heading(doc, f"{i}. {pt['modern_issue']}", 3)
                add_para(doc, f"历史关联：{pt['historical_connection']}", indent=True)
                add_para(doc, f"当代启示：{pt['contemporary_reflection']}", indent=True)
            doc.add_paragraph()

            # ── 第四幕：春秋笔法 ────────────────────────────────
            add_heading(doc, "第四幕 · 春秋笔法", 2)
            sat = ep["spring_autumn_transition"]
            if sat.get("from_this_volume_ep1"):
                prev = sat["from_this_volume_ep1"]
                add_para(doc, f"上接：{prev['preceding_ep']}", bold=True)
                add_para(doc, prev["transition_sentence"].strip(), indent=True)
            if sat.get("to_ep2"):
                nxt = sat["to_ep2"]
                add_para(doc, f"下承：{nxt['next_ep']}", bold=True)
                add_para(doc, nxt["forward_context"].strip(), indent=True)
            if sat.get("to_modern_history") and sat["to_modern_history"].get("series_conclusion"):
                sc = sat["to_modern_history"]["conclusion_context"]
                add_para(doc, "全系列结语", bold=True)
                add_para(doc, sc.strip(), indent=True)
            doc.add_paragraph()

            # ── 附录：知识链 ──────────────────────────────────
            add_heading(doc, "附录 · 知识链", 2)
            chains = ep["knowledge_chains"]
            for ch_id, ch in chains.items():
                add_heading(doc, f"{ch['chain_id']}：{ch['chain_title']}", 3)
                add_para(doc, f"类型：{ch['chain_type']}", bold=True)
                add_para(doc, f"核心规律：{ch['core_pattern']}", indent=True)
                add_para(doc, ch["narrative"].strip(), indent=True)
                add_para(doc, "关键节点：", bold=True)
                for nd in ch["key_nodes"]:
                    add_bullet(doc, f"{nd['node']} → {nd['answer']}")
                doc.add_paragraph()

            # ── 高频考点 ─────────────────────────────────────
            add_heading(doc, "附录 · 高频考点速记", 2)
            for pt in ep["high_frequency_points"]:
                add_bullet(doc, pt)
            doc.add_paragraph()

            # ── 核心概念 ─────────────────────────────────────
            add_heading(doc, "附录 · 核心概念", 2)
            for cpt in ep["key_concepts"]:
                p = doc.add_paragraph()
                run = p.add_run(f"{cpt['concept']}：")
                run.bold = True
                run.font.size = Pt(11)
                run2 = p.add_run(cpt["definition"].strip())
                run2.font.size = Pt(10.5)
                run3 = p.add_run(f"\n应试提示：{cpt['exam_tip']}")
                run3.italic = True
                run3.font.size = Pt(9.5)
            doc.add_page_break()

        doc.save(out_path)
        size = os.path.getsize(out_path)
        print(f"[DOCX] 写入成功：{out_path}（{size/1024:.1f} KB）")


# ── 主函数 ───────────────────────────────────────────────────
def main():
    print("=" * 50)
    print("共和新生 · 电子书生成器")
    print("卷三：中国近现代史（1840-1949）")
    print("=" * 50)

    episodes = load_episodes()
    print(f"已加载 {len(episodes)} 集数据")

    # 输出路径（默认桌面）
    desktop = os.path.join(os.path.expanduser("~"), "Desktop")

    # MD 输出
    md_path = os.path.join(desktop, "共和新生_v3_电子书.md")
    md_renderer = ModernHistoryMD(episodes)
    md_renderer.save(md_path)

    # DOCX 输出
    docx_path = os.path.join(desktop, "共和新生_v3_电子书.docx")
    docx_renderer = ModernHistoryDOCX(episodes)
    docx_renderer.render(docx_path)

    print("=" * 50)
    print("[OK] All done!")
    print(f"[MD] {md_path}")
    print(f"[DOCX] {docx_path}")


if __name__ == "__main__":
    main()
